---
metadata:
    processor: XMLParser
    execute:
        - method: _rpc
          kwargs:
              get: "<get-configuration/>"

interfaces:
    _process: unnecessary
    interface:
        _process:
            - xpath: "interfaces/interface"
              key: name
              from: interfaces.0
        name:
            _process: unnecessary
        hold-time:
            _process: not_implemented
            config:
                _process: not_implemented
                down:
                    _process: not_implemented
                up:
                    _process: not_implemented
        config:
            _process: unnecessary
            name:
                _process:
                    - mode: value
                      value: "{{ interface_key }}"
            type:
                _process:
                    - mode: map
                      xpath: name
                      regexp: "(?P<value>[a-z]+).*"
                      map:
                          ge: ethernetCsmacd
                          xe: ethernetCsmacd
                          et: ethernetCsmacd
                          irb: ethernetCsmacd
                          me: ethernetCsmacd
                          vlan: ethernetCsmacd
                          lo: softwareLoopback
                          ae: ieee8023adLag
            enabled:
                _process:
                    - mode: is_absent
                      xpath: "disable"
            description:
                _process:
                    - xpath: description
            mtu:
                _process:
                    - xpath: mtu
        subinterfaces:
            _process: unnecessary
            subinterface:
                _process:
                    - xpath: "unit"
                      key: name
                index:
                    _process: unnecessary
                config:
                    _process: unnecessary
                    index:
                        _process: not_implemented
                    name:
                        _process:
                            - mode: value
                              value: "{{ subinterface_key }}"
                    enabled:
                        _process:
                            - mode: is_absent
                              xpath: "disable"
                    description:
                        _process:
                            - xpath: description
