---
metadata:
    parser: TextParser

ipv4:
    _parse: unnecessary
    config:
        _parse: unnecessary
        enabled:
            _parse: # TODO look at this one, I think this is different depending on IOS version
                mode: is_absent
                regexp: "(?P<value>^\\W*switchport$)"
                from: "{{ bookmarks['parent'] }}"
        mtu:
            _parse: not_implemented
    addresses:
        _parse: unnecessary
        address:
            _parse:
                mode: block
                regexp: "(?P<block>ip address (?P<key>(?P<ip>.*)) (?P<prefix>([0-255]|\\.)*)(?P<secondary> secondary)*)$"
                from: "{{ bookmarks['parent'] }}"
            ip:
                _parse: unnecessary
            config:
                _parse: unnecessary
                ip:
                    _parse:
                        mode: value
                        value: "{{ extra_vars.ip }}"
                prefix-length:
                    _parse:
                        mode: value
                        value: "{{ extra_vars.prefix|netmask_to_cidr }}"
            vrrp:
                _parse: not_implemented
                vrrp-group:
                    _parse: not_implemented
                    virtual-router-id:
                        _parse: not_implemented
                    config:
                        _parse: not_implemented
                        virtual-address:
                            _parse: not_implemented
                        priority:
                            _parse: not_implemented
                        preempt:
                            _parse: not_implemented
                        advertisement-interval:
                            _parse: not_implemented
                        virtual-router-id:
                            _parse: not_implemented
                        preempt-delay:
                            _parse: not_implemented
                        accept-mode:
                            _parse: not_implemented
    unnumbered:
        _parse: not_implemented
        config:
            _parse: not_implemented
            enabled:
                _parse: not_implemented
        interface-ref:
            _parse: not_implemented
            config:
                _parse: not_implemented
                interface:
                    _parse: not_implemented
                subinterface:
                    _parse: not_implemented
    neighbors:
        _parse: not_implemented
        neighbor:
            _parse: not_implemented
            ip:
                _parse: not_implemented
            config:
                _parse: not_implemented
                ip:
                    _parse: not_implemented
                link-layer-address:
                    _parse: not_implemented
